import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'leave | Viewpoint Ministries International' },
  description:
    'The Reality of You, Your Faith, and Your Health W_ Dr. Deji Alabi by Viewpoint Ministries | Aug 11, 2021 | PODCASTS…',
  alternates: { canonical: '/tag/leave/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tag tag-leave tag-136 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_archives dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('tag/leave') }}
    />
  )
}
