// Generated by workflow 706 (convert-clone-to-routes.mjs). Edit the template in
// FFC-Cloudflare-Automation/assets/clone-enhance.tsx, not this copy.
'use client'

import { useEffect } from 'react'

/**
 * The entire client-side runtime of an FFC static clone.
 *
 * A captured WordPress site arrives carrying ~1.9 MB of jQuery, jQuery Migrate,
 * Underscore, the Divi theme bundle, Divi Plus, Swiper, Hustle, MediaElement, a
 * cookie-consent plugin and two analytics beacons. Measured against the DOM
 * actually captured for this site, that payload exists to serve exactly two
 * behaviours: a hamburger menu and a scroll-in fade. Everything else Divi ships
 * a handler for — toggles, accordions, tabs, sliders, video overlays, counters,
 * countdowns, lightboxes, contact forms — appears on zero pages.
 *
 * It is a client component rather than a `<script>` in the captured markup for
 * a reason that only shows up in one direction: the fragment is injected with
 * `dangerouslySetInnerHTML`, and a `<script>` arriving that way runs on a cold
 * load (static export writes it into the HTML the browser parses) and silently
 * does not run on a client-side navigation. A behaviour present or absent
 * depending on how the visitor arrived is worse than either.
 *
 * Three properties are deliberate and worth keeping if this is ever edited:
 *
 *   - **No JavaScript is required to read the site.** The capture strips Divi's
 *     `.et-waypoint{opacity:0}` rule, so content is painted whether or not this
 *     runs. Animation is enhancement; visibility never is.
 *   - **Nothing is built from a string.** No innerHTML, no eval, no injected
 *     script. The mobile menu is a `cloneNode()` of markup the server already
 *     sent, which is why no page text can become markup here.
 *   - **Nothing leaves the page.** No fetch, no beacon, no third-party host.
 */

/** Modules that can own a hamburger: the Divi menu module and its fullwidth twin. */
const MENU_MODULE = '.et_pb_menu, .et_pb_fullwidth_menu'

type Teardown = () => void

/**
 * Wire one menu module's hamburger.
 *
 * Divi ships the toggle as a bare `<span>` and builds the mobile list in
 * JavaScript. Both are reproduced, with the accessibility defects fixed rather
 * than reproduced: the span becomes a real button to the accessibility tree, it
 * carries its expanded state, and it answers Enter and Space.
 */
function wireMenu(module: Element): Teardown | null {
  const bar = module.querySelector<HTMLElement>('.mobile_menu_bar')
  const nav = module.querySelector<HTMLElement>('.mobile_nav')
  const source = module.querySelector<HTMLElement>(
    '.et_pb_menu__menu ul.et-menu, .et-menu-nav ul.et-menu'
  )
  if (!bar || !nav || !source) return null

  // Built once, on first open. A menu nobody opens costs nothing.
  let list: HTMLElement | null = null
  let open = false

  bar.setAttribute('role', 'button')
  bar.setAttribute('tabindex', '0')
  bar.setAttribute('aria-label', 'Toggle menu')
  bar.setAttribute('aria-expanded', 'false')

  const build = (): HTMLElement => {
    if (list) return list
    // cloneNode, not innerHTML: the markup is copied as a parsed tree, so there
    // is no string for anything to be injected into.
    list = source.cloneNode(true) as HTMLElement
    list.removeAttribute('id')
    list.className = 'et_mobile_menu'
    // The clone carries the desktop menu's ids; a duplicate id is invalid and
    // breaks in-page anchors and label targeting.
    list.querySelectorAll('[id]').forEach((el) => el.removeAttribute('id'))
    list.style.display = 'none'
    nav.appendChild(list)
    return list
  }

  const setOpen = (next: boolean) => {
    const el = build()
    open = next
    el.style.display = next ? 'block' : 'none'
    bar.setAttribute('aria-expanded', next ? 'true' : 'false')
    nav.classList.toggle('opened', next)
    nav.classList.toggle('closed', !next)
  }

  const onClick = (event: Event) => {
    event.preventDefault()
    setOpen(!open)
  }
  const onKeyDown = (event: KeyboardEvent) => {
    if (event.key !== 'Enter' && event.key !== ' ' && event.key !== 'Spacebar') return
    event.preventDefault()
    setOpen(!open)
  }
  // Escape closes, and focus goes back to the control that opened it —
  // otherwise a keyboard user is stranded inside a list they cannot dismiss.
  const onEscape = (event: KeyboardEvent) => {
    if (event.key !== 'Escape' && event.key !== 'Esc') return
    if (!open) return
    setOpen(false)
    bar.focus()
  }

  bar.addEventListener('click', onClick)
  bar.addEventListener('keydown', onKeyDown)
  module.addEventListener('keydown', onEscape as EventListener)

  return () => {
    bar.removeEventListener('click', onClick)
    bar.removeEventListener('keydown', onKeyDown)
    module.removeEventListener('keydown', onEscape as EventListener)
  }
}

/**
 * Reveal Divi's scroll-in elements.
 *
 * Divi hides `.et-waypoint` at `opacity: 0` and reveals it from a scroll
 * handler. The capture removes that hiding rule, so this only adds the class
 * that starts the keyframe animation the stylesheet already defines. If
 * IntersectionObserver is missing, every element is revealed immediately — the
 * failure mode is "no animation", never "no content".
 */
function wireWaypoints(): Teardown | null {
  const targets = document.querySelectorAll<HTMLElement>('.et-waypoint:not(.et-animated)')
  if (!targets.length) return null

  if (typeof window.IntersectionObserver !== 'function') {
    targets.forEach((el) => el.classList.add('et-animated'))
    return null
  }

  const observer = new window.IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (!entry.isIntersecting) continue
        entry.target.classList.add('et-animated')
        observer.unobserve(entry.target)
      }
    },
    { rootMargin: '0px 0px -10% 0px' }
  )
  targets.forEach((el) => observer.observe(el))
  return () => observer.disconnect()
}

export default function CloneEnhance() {
  useEffect(() => {
    const teardowns: Teardown[] = []
    document.querySelectorAll(MENU_MODULE).forEach((module) => {
      const off = wireMenu(module)
      if (off) teardowns.push(off)
    })
    const offWaypoints = wireWaypoints()
    if (offWaypoints) teardowns.push(offWaypoints)
    return () => teardowns.forEach((off) => off())
  }, [])

  return null
}
