import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title:
    'This is Essential for Your Continuous & Victorious Living | Viewpoint Ministries International',
  description:
    'Allow me to congratulate you - thus far, the Lord has been so good to you. If not for the Lord, where would you be? Even as we gradually move toward the end ...',
  alternates: { canonical: '/this-is-essential-for-your-continuous-victorious-living/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1284 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('this-is-essential-for-your-continuous-victorious-living'),
      }}
    />
  )
}
