import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'What Is In The Name? [Audio] | Viewpoint Ministries International',
    description:
      'https://anchor.fm/s/50014258/podcast/rss Summary “What Is In the Name?” To support this podcast please follow this link www.anchor.fm/viewpointministries/su ...',
    canonical: '/what-is-in-the-name-audio/',
  }),
  title: { absolute: 'What Is In The Name? [Audio] | Viewpoint Ministries International' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1433 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('what-is-in-the-name-audio') }}
    />
  )
}
