import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title:
    'The Church, The Christian & Christian Life W/ Pastor Akinola Elesinla | Viewpoint Ministries International',
  description:
    'More than ever, the Church and the Christian need to be and do the best for God. To do so however, there is a need for proper understanding of the church, t ...',
  alternates: { canonical: '/the-church-the-christian-christian-life-w-pastor-akinola-elesinla/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-875 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent(
          'the-church-the-christian-christian-life-w-pastor-akinola-elesinla'
        ),
      }}
    />
  )
}
