import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Your Mansion Await You If You Can Do This | Viewpoint Ministries International',
    description:
      'Jesus said many mansions are available in His father’s house (John 14:2), this is for the people who are dead to sins but alive to God; Do not forget that t ...',
    canonical: '/your-mansion-await-you-if-you-can-do-this/',
  }),
  title: {
    absolute: 'Your Mansion Await You If You Can Do This | Viewpoint Ministries International',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1962 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('your-mansion-await-you-if-you-can-do-this'),
      }}
    />
  )
}
