import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title:
    'Conforming to The New Life in Christ w/Dr. Sola Famakin | Viewpoint Ministries International',
  description:
    'To be in Christ is to take on the life of Christ, but it is impossible to take on His life without knowing Him; We cannot know Him without accept that He di ...',
  alternates: { canonical: '/conforming-to-the-new-life-in-christ-w-dr-sola-famakin/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-715 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('conforming-to-the-new-life-in-christ-w-dr-sola-famakin'),
      }}
    />
  )
}
