import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      '(1 of 3) Independence_ Leadership Character in Government & Politics - The State of Nigeria w_ Mr. Femi Odedeyi | Viewpoint Ministries International',
    description: 'Leadership Character in Government & Politics',
    canonical:
      '/1-of-3-independence-leadership-character-in-government-politics-the-state-of-nigeria-w-mr-femi-odedeyi/',
  }),
  title: {
    absolute:
      '(1 of 3) Independence_ Leadership Character in Government & Politics - The State of Nigeria w_ Mr. Femi Odedeyi | Viewpoint Ministries International',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-727 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent(
          '1-of-3-independence-leadership-character-in-government-politics-the-state-of-nigeria-w-mr-femi-odedeyi'
        ),
      }}
    />
  )
}
