import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'financial | Viewpoint Ministries International',
    description:
      'Fear: The Enemy of Progress by Viewpoint Ministries | Jul 31, 2021 | MY VIEW What makes you frightened? What makes you terrified? What causes you to be…',
    canonical: '/tag/financial/',
  }),
  title: { absolute: 'financial | Viewpoint Ministries International' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tag tag-financial tag-116 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_archives dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('tag/financial') }}
    />
  )
}
