import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'The Spiritual-Fitted Life 2.0 | Viewpoint Ministries International' },
  description:
    'This is a continuation of the Spiritual-Fitted Life that took place on May 21, 2023. You can watch the first edition of Spiritual-Fitted Life here However, ...',
  alternates: { canonical: '/the-spiritual-fitted-life-2-0/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-17680 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('the-spiritual-fitted-life-2-0') }}
    />
  )
}
