import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Why Do We Need Wisdom? | Viewpoint Ministries International' },
  description:
    'Wisdom is indispensable in your daily living - without wisdom life, becomes struggles and difficulties becomes daily occurrent. You should not engage in any ...',
  alternates: { canonical: '/why-do-we-need-wisdom-2/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-679 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('why-do-we-need-wisdom-2') }}
    />
  )
}
