import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Gossip About God | Viewpoint Ministries International' },
  description:
    'There is often excitement when we hear scandalous news about someone we know. What follows next is usually the temptation to share what we have heard and ke ...',
  alternates: { canonical: '/gossip-about-god/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1714 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('gossip-about-god') }}
    />
  )
}
