import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'The Comforter: Episode 5 of Difficult Seasons | Viewpoint Ministries International',
    description:
      'Welcome to My View, I ended the last episode by saying you should reevaluate your life and make necessary adjustments and that if you trust God for peace, y ...',
    canonical: '/the-comforter-episode-5-of-difficult-seasons/',
  }),
  title: {
    absolute: 'The Comforter: Episode 5 of Difficult Seasons | Viewpoint Ministries International',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-2785 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('the-comforter-episode-5-of-difficult-seasons'),
      }}
    />
  )
}
