import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Uncategorized | Viewpoint Ministries International',
    description:
      'Who Is This Baby Jesus? by Viewpoint Ministries | Dec 26, 2022 | CHRISTIANITY & POLITICS , eTRACTS , HEALTH , LET’S TALK ABOUT JESUS , MY VIEW , PODCASTS…',
    canonical: '/category/uncategorized/',
  }),
  title: { absolute: 'Uncategorized | Viewpoint Ministries International' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-uncategorized category-1 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_archives dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('category/uncategorized') }}
    />
  )
}
