import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'End It with Praise: Do not Be Ungrateful | Viewpoint Ministries International',
    description:
      'Congratulations! You are now in the final stretch of the year 2021. I hope you are in the mood of gratitude, and if you think you have nothing to be gratefu ...',
    canonical: '/end-it-with-praise-do-not-be-ungrateful/',
  }),
  title: {
    absolute: 'End It with Praise: Do not Be Ungrateful | Viewpoint Ministries International',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1329 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('end-it-with-praise-do-not-be-ungrateful'),
      }}
    />
  )
}
