import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title:
    'When The Immortal Uses The Mortal - God Can Use You Too (Audio) | Viewpoint Ministries International',
  description:
    'Today, there are people facing life challenges. Allow God to use you to bless them...',
  alternates: { canonical: '/when-the-immortal-uses-the-mortal-god-can-use-you-too-audio/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1123 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('when-the-immortal-uses-the-mortal-god-can-use-you-too-audio'),
      }}
    />
  )
}
