// Generated by workflow 706 (convert-clone-to-routes.mjs). Edit the template in
// FFC-Cloudflare-Automation/assets/ffc-footer.tsx, not this copy.
import Link from 'next/link'
import { siteConfig } from '@/lib/site.config'

/**
 * FFC-standard attribution footer, rendered site-wide below the cloned page
 * chrome (the cloned pages keep their own visual footer; this strip carries the
 * Free For Charity program attribution and the legal/policy links).
 *
 * It replaces the template's marketing footer rather than joining it: that one
 * links to `/#mission`, `/#programs` and the rest of the template home page,
 * anchors that do not exist once the charity's own front page takes over the
 * root route. A footer full of links to nothing is a worse outcome than a
 * smaller footer.
 *
 * Footer-standard checklist items covered here:
 *   1. Charity identity — name + EIN, linked to the Candid transparency profile.
 *   2. Permanent "Supported by Free For Charity" attribution.
 *   3. "Supported Charity Login" link to the FFC hub.
 *   4. Copyright line with the build year and the charity's name.
 *   5. Policy links.
 *
 * The 501(c)(3) status line and the Candid seal are Level 2 items and are shown
 * only when siteConfig carries a real EIN — a pre-501c3 site claiming the
 * status would be a false legal claim, so the absence is rendered as an
 * absence rather than filled in.
 */
export default function FfcFooter() {
  const year = new Date().getFullYear()
  const ein = siteConfig.ein?.trim()
  const taxStatusLabel = siteConfig.taxStatusLabel.trim()
  const policyLinks = [
    { name: 'Privacy Policy', href: '/privacy-policy' },
    { name: 'Cookie Policy', href: '/cookie-policy' },
    { name: 'Terms of Service', href: '/terms-of-service' },
    { name: 'Donation Policy', href: '/donation-policy' },
    { name: 'Vulnerability Disclosure', href: '/vulnerability-disclosure-policy' },
  ]
  const identity = ein ? `${siteConfig.name} — EIN ${ein}` : siteConfig.name

  return (
    <footer className="ffc-footer" aria-label="Site information and policies">
      <div className="ffc-footer__inner">
        <p className="ffc-footer__identity">
          {ein && siteConfig.guidestar?.profileUrl ? (
            <a
              href={siteConfig.guidestar.profileUrl}
              target="_blank"
              rel="noopener noreferrer"
              // The accessible name must contain the visible text
              // (axe "label-content-name-mismatch"), so lead with it.
              aria-label={`${identity} — view the nonprofit profile on Candid`}
            >
              {identity}
            </a>
          ) : (
            identity
          )}
        </p>

        <ul className="ffc-footer__links">
          {policyLinks.map((link) => (
            <li key={link.href}>
              <Link href={link.href}>{link.name}</Link>
            </li>
          ))}
          <li>
            <a href="https://freeforcharity.org/hub/" target="_blank" rel="noopener noreferrer">
              Supported Charity Login
            </a>
          </li>
        </ul>

        {/* The FFC footer standard's bottom bar, word for word as the template
            renders it. The wording is not decoration: tests/copyright.spec.ts
            asserts on this exact phrasing, and the "Supported by" clause is a
            permanent program attribution that must never be removed or hidden
            when a site is customized. */}
        <p className="ffc-footer__legal">
          © {year} All Rights Are Reserved by {siteConfig.name}
          {taxStatusLabel ? ` ${taxStatusLabel}` : ''}
          {' | Supported by '}
          <a href={siteConfig.supportedBy.url} target="_blank" rel="noopener noreferrer">
            {siteConfig.supportedBy.name}
          </a>
          {siteConfig.parentOrg && (
            <>
              {' | A project of '}
              <a href={siteConfig.parentOrg.url} target="_blank" rel="noopener noreferrer">
                {siteConfig.parentOrg.name}
              </a>
            </>
          )}
        </p>
      </div>
    </footer>
  )
}
