// Generated by workflow 706 (convert-clone-to-routes.mjs). Edit the template in
// FFC-Cloudflare-Automation/assets/ffc-footer.tsx, not this copy.
import Link from 'next/link'
import PendingNote from '@/components/ui/PendingNote'
import { isPending, siteConfig, type PendingField } from '@/lib/site.config'

// Footer-standard fields the charity has not supplied yet (siteConfig.pending)
// are listed here with a visible "awaiting information" placeholder, as plain
// text — never a link (ported from
// FreeForCharity/FFC-IN-FFC_Single_Page_Template#483). The captured pages'
// own footer carries the charity's email, phone and social links, so this
// strip is where a gap in the footer standard becomes visible.
const PENDING_LABELS: Record<PendingField, string> = {
  email: 'E-mail',
  phone: 'Phone',
  address: 'Address',
  ein: 'EIN',
  guidestar: 'GuideStar / Candid Profile',
  social: 'Social Media',
  team: 'Leadership Team',
  donationUrl: 'Donation Page',
  volunteerUrl: 'Volunteer Page',
}

/**
 * FFC-standard attribution footer, rendered site-wide below the cloned page
 * chrome (the cloned pages keep their own visual footer; this strip carries the
 * Free For Charity program attribution and the legal/policy links).
 *
 * It replaces the template's marketing footer rather than joining it: that one
 * links to `/#mission`, `/#programs` and the rest of the template home page,
 * anchors that do not exist once the charity's own front page takes over the
 * root route. A footer full of links to nothing is a worse outcome than a
 * smaller footer.
 *
 * Footer-standard checklist items covered here:
 *   1. Charity identity — name + EIN, linked to the Candid transparency profile.
 *   2. Permanent "Supported by Free For Charity" attribution.
 *   3. "Supported Charity Login" link to the FFC hub.
 *   4. Copyright line with the build year and the charity's name.
 *   5. Policy links.
 *
 * The EIN and the Candid transparency link are Level 2 items. The shared
 * schema lets both be empty (FreeForCharity/FFC-IN-FFC_Single_Page_Template#483),
 * so a value the charity has not supplied is left EMPTY and listed in
 * `siteConfig.pending` rather than carrying the template's (Free-For-Charity)
 * default: the identity line then shows the name alone and the pending list
 * below shows the placeholder. The Candid link renders only when both the EIN
 * and the charity's own profile URL are set.
 */
export default function FfcFooter() {
  const year = new Date().getFullYear()
  const ein = isPending('ein') ? '' : (siteConfig.ein?.trim() ?? '')
  const candidUrl = isPending('guidestar') ? '' : (siteConfig.guidestar?.profileUrl?.trim() ?? '')
  const pending = [...new Set(siteConfig.pending ?? [])]
  const taxStatusLabel = siteConfig.taxStatusLabel?.trim() ?? ''
  const policyLinks = [
    { name: 'Privacy Policy', href: '/privacy-policy' },
    { name: 'Cookie Policy', href: '/cookie-policy' },
    { name: 'Terms of Service', href: '/terms-of-service' },
    { name: 'Donation Policy', href: '/donation-policy' },
    { name: 'Vulnerability Disclosure', href: '/vulnerability-disclosure-policy' },
  ]
  const identity = ein ? `${siteConfig.name} — EIN ${ein}` : siteConfig.name

  return (
    <footer className="ffc-footer" aria-label="Site information and policies">
      <div className="ffc-footer__inner">
        <p className="ffc-footer__identity">
          {ein && candidUrl ? (
            <a
              href={candidUrl}
              target="_blank"
              rel="noopener noreferrer"
              // The accessible name must contain the visible text
              // (axe "label-content-name-mismatch"), so lead with it.
              aria-label={`${identity} — view the nonprofit profile on Candid`}
            >
              {identity}
            </a>
          ) : (
            identity
          )}
        </p>

        {pending.length > 0 && (
          <ul className="ffc-footer__pending" aria-label="Information awaited from the charity">
            {pending.map((field) => (
              <li key={field}>
                <span className="ffc-footer__pending-label">{PENDING_LABELS[field]}:</span>{' '}
                <PendingNote />
              </li>
            ))}
          </ul>
        )}

        <ul className="ffc-footer__links">
          {policyLinks.map((link) => (
            <li key={link.href}>
              <Link href={link.href}>{link.name}</Link>
            </li>
          ))}
          <li>
            <a href={siteConfig.supportedBy.hubUrl} target="_blank" rel="noopener noreferrer">
              Supported Charity Login
            </a>
          </li>
        </ul>

        {/* The FFC footer standard's bottom bar, word for word as the template
            renders it. The wording is not decoration: tests/copyright.spec.ts
            asserts on this exact phrasing, and the "Supported by" clause is a
            permanent program attribution that must never be removed or hidden
            when a site is customized. */}
        <p className="ffc-footer__legal">
          © {year} All Rights Are Reserved by {siteConfig.name}
          {taxStatusLabel ? ` ${taxStatusLabel}` : ''}
          {' | Supported by '}
          <a href={siteConfig.supportedBy.url} target="_blank" rel="noopener noreferrer">
            {siteConfig.supportedBy.name}
          </a>
          {siteConfig.parentOrg && (
            <>
              {' | A project of '}
              <a href={siteConfig.parentOrg.url} target="_blank" rel="noopener noreferrer">
                {siteConfig.parentOrg.name}
              </a>
            </>
          )}
        </p>
      </div>
    </footer>
  )
}
