import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: 'Sharing | Viewpoint Ministries International',
  description:
    'Sharing a Meal by Viewpoint Ministries | May 10, 2022 | MY VIEW God wants us to care for others. There are diverse ways to do this, but one of the most…',
  alternates: { canonical: '/tag/sharing/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tag tag-sharing tag-270 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_archives dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('tag/sharing') }}
    />
  )
}
