import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Pathway | Viewpoint Ministries International' },
  description:
    'The Glorious Pathway by Viewpoint Ministries | Apr 17, 2022 | MY VIEW , PODCASTS [Echo From Sharing in His Crucifixion] The way of the cross is not rosy…',
  alternates: { canonical: '/tag/pathway/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tag tag-pathway tag-275 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_archives dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('tag/pathway') }}
    />
  )
}
