import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'The Cure for Stinking Thinking | Viewpoint Ministries International',
    description:
      'Your thoughts are powerful, they shape the direction of your life. That is why the bible gives us direction on what we should focus on. If you have been str ...',
    canonical: '/the-cure-for-stinking-thinking/',
  }),
  title: { absolute: 'The Cure for Stinking Thinking | Viewpoint Ministries International' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1941 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('the-cure-for-stinking-thinking') }}
    />
  )
}
