import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Assurance: You Are Not Alone | Viewpoint Ministries International',
    description:
      'No matter the events or circumstances, the presence of the Lord is with you, and you have the assurance that all is well. Remember, you are not created by a ...',
    canonical: '/assurance-you-are-not-alone-2/',
  }),
  title: { absolute: 'Assurance: You Are Not Alone | Viewpoint Ministries International' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-666 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('assurance-you-are-not-alone-2') }}
    />
  )
}
