import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'words | Viewpoint Ministries International' },
  description:
    'Wise Words by Viewpoint Ministries | May 16, 2022 | MY VIEW Words are important. Words can heal, or they can hurt. Try to encourage all who cross your path…',
  alternates: { canonical: '/tag/words/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tag tag-words tag-232 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_archives dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('tag/words') }}
    />
  )
}
