import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: 'The Word Is Alive | Viewpoint Ministries International',
  description:
    'The word of the Lord is the truth and is powerful. God’s word is alive and awakens, convicts, and changes the inner man. Let the word of God dwell in you ri ...',
  alternates: { canonical: '/the-word-is-alive/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1872 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('the-word-is-alive') }}
    />
  )
}
