import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: 'Strength To Forgive When You Don’t Want To | Viewpoint Ministries International',
  description:
    'God wants you to treat others as you wish to be treated. And since you want to be forgiven for the mistakes you have made, you must extend forgiveness to ot ...',
  alternates: { canonical: '/strength-to-forgive-when-you-dont-want-to/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-2359 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('strength-to-forgive-when-you-dont-want-to'),
      }}
    />
  )
}
