import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: {
    absolute:
      'Difficult Seasons: Episode 4 – You can only find peace in God. | Viewpoint Ministries International',
  },
  description:
    'Are you oppressed, depressed, hated, falsely accused and condemned? don’t allow anyone who did not create you to downgrade you. Re-evaluate your life and ma ...',
  alternates: { canonical: '/difficult-seasons-episode-4-you-can-only-find-peace-in-god/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-2784 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('difficult-seasons-episode-4-you-can-only-find-peace-in-god'),
      }}
    />
  )
}
