import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: 'Parents | Viewpoint Ministries International',
  description:
    'The Voice – Difficult Seasons: Episode 6 by Viewpoint Ministries | Apr 10, 2021 | MY VIEW Today I like to speak to you by asking you this question, “whose…',
  alternates: { canonical: '/tag/parents/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tag tag-parents tag-47 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_archives dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('tag/parents') }}
    />
  )
}
