import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'End It With Praise: Don’t Be Ungrateful [Audio] | Viewpoint Ministries International',
    description:
      'https://anchor.fm/s/50014258/podcast/rss Summary In this episode, we bring you a message “End It With Praise: Don’t Be Ungrateful” To support this podcast p ...',
    canonical: '/end-it-with-praise-dont-be-ungrateful-audio/',
  }),
  title: {
    absolute:
      'End It With Praise: Don’t Be Ungrateful [Audio] | Viewpoint Ministries International',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1344 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('end-it-with-praise-dont-be-ungrateful-audio'),
      }}
    />
  )
}
