import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      'Marketplace Identity Crisis and The Invisible War (Audio) | Viewpoint Ministries International',
    description:
      'You are responsible for the reflection of the light in your family, your neighborhood, your community, your workplace or business, your school, your state, ...',
    canonical: '/marketplace-identity-crisis-and-the-invisible-war-2/',
  }),
  title: {
    absolute:
      'Marketplace Identity Crisis and The Invisible War (Audio) | Viewpoint Ministries International',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1022 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('marketplace-identity-crisis-and-the-invisible-war-2'),
      }}
    />
  )
}
