import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Bible Tracts Ministry | Viewpoint Ministries International' },
  description:
    'Viewpoint Ministries International uses Bible Tracts Ministry to introduce people to Jesus Christ. In July 2022, volunteers delivered 1,000 tracts and 150 b ...',
  alternates: { canonical: '/bibletractsministry/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-8867 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_pb_pagebuilder_layout et_no_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('bibletractsministry') }}
    />
  )
}
