import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'wealth | Viewpoint Ministries International' },
  description:
    'Wealth Obtained At The Expense of Your Spirit and Your Health (Audio) by Viewpoint Ministries | May 21, 2022 | MY VIEW , PODCASTS…',
  alternates: { canonical: '/tag/wealth/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tag tag-wealth tag-316 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_archives dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('tag/wealth') }}
    />
  )
}
