import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Home | Viewpoint Ministries International',
    description:
      'Viewpoint Ministries International, Inc. A Registered 501(c)(3) Nonprofit Organization Together Let’s “…Contend Earnestly For The Faith…” (Jude 1:3). VISION ...',
    canonical: '/',
  }),
  title: { absolute: 'Home | Viewpoint Ministries International' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone home wp-singular page-template-default page page-id-2 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_pb_pagebuilder_layout et_no_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('index') }}
    />
  )
}
