// Generated by workflow 706 (integrate-clone-into-nextjs.mjs). Edit the
// template in FFC-Cloudflare-Automation/assets/clone-sitemap.ts, not this copy.
//
// This repo no longer has app routes. The site is the static capture under
// `public/`, which `output: 'export'` copies verbatim into `out/`, so a sitemap
// built from a hand-maintained list of `src/app/**/page.tsx` paths would
// describe eight routes that no longer exist and none of the several hundred
// pages that do.
//
// The list is therefore derived from `public/` at build time rather than
// declared. That is not just less work to maintain: the property the previous
// version asserted in a unit test — the sitemap cannot silently fall behind
// what is published — becomes structural here, because there is no second copy
// of the truth to drift from.
import { readdirSync } from 'node:fs'
import { join } from 'node:path'
import type { MetadataRoute } from 'next'
import { siteUrl } from '@/lib/site.config'

export const dynamic = 'force-static'

type SitemapEntry = {
  path: string
  changeFrequency: MetadataRoute.Sitemap[number]['changeFrequency']
  priority: number
}

export const PUBLIC_DIR = join(process.cwd(), 'public')

// Directories under public/ that hold assets rather than pages. `_ffc-assets`
// is the capture's own asset tree; anything dot- or underscore-prefixed is
// tooling. Excluding them by name keeps a stray `index.html` in an asset folder
// out of the sitemap.
const NOT_A_PAGE_DIR = /^[._]/

/**
 * Every directory under public/ that owns an index.html, expressed as the URL
 * path a static host serves it at ('/', '/about-us', '/a/b').
 */
export function discoverExportedPages(dir: string = PUBLIC_DIR, prefix = ''): string[] {
  let entries
  try {
    entries = readdirSync(dir, { withFileTypes: true })
  } catch {
    // A repo without a capture in public/ yet is not an error; it has no pages.
    return []
  }

  const out: string[] = []
  for (const entry of entries) {
    if (entry.isFile() && entry.name === 'index.html') {
      out.push(prefix === '' ? '/' : prefix)
    }
    if (entry.isDirectory()) {
      if (NOT_A_PAGE_DIR.test(entry.name)) continue
      out.push(...discoverExportedPages(join(dir, entry.name), `${prefix}/${entry.name}`))
    }
  }
  return out
}

// Priority schema: 1.0 for the front page, 0.5 for everything else. The capture
// carries no signal that would distinguish a section landing page from a post,
// so inventing a finer gradient here would be decoration, not information.
export const routes: readonly SitemapEntry[] = discoverExportedPages()
  .sort()
  .map((path) => ({
    path,
    changeFrequency: 'monthly' as const,
    priority: path === '/' ? 1.0 : 0.5,
  }))

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()
  return routes.map((entry) => ({
    url: siteUrl(entry.path),
    lastModified: now,
    changeFrequency: entry.changeFrequency,
    priority: entry.priority,
  }))
}
