// Generated by workflow 706 (convert-clone-to-routes.mjs). Edit the template in
// FFC-Cloudflare-Automation/assets/clone-routes-sitemap.ts, not this copy.
//
// The route list is DERIVED from `src/app`, not declared. A hand-maintained
// array is a second copy of the truth, and on a site of several hundred
// converted pages it falls behind the first time a page is added or renamed —
// silently, because a sitemap listing a route that does not exist and a sitemap
// missing one that does both render as valid XML. Deriving it makes "the
// sitemap cannot disagree with what is published" structural rather than a
// property a unit test has to keep asserting.
import { readdirSync } from 'node:fs'
import type { Dirent } from 'node:fs'
import { join } from 'node:path'
import type { MetadataRoute } from 'next'
import { siteUrl } from '@/lib/site.config'

export const dynamic = 'force-static'

export const APP_DIR = join(process.cwd(), 'src', 'app')

// Next.js route-group and private folders: `(group)` does not appear in the
// URL and `_private` is not a route at all, so neither belongs in a sitemap.
const NOT_A_ROUTE_DIR = /^[(_[]/

/** Every static route under src/app, as the path it is served at. */
export function discoverRoutes(dir: string = APP_DIR, prefix = ''): string[] {
  // Typed rather than inferred: this file ships verbatim into every FFC-EX
  // repo, and an implicitly-`any` binding trips `noImplicitAny` in any of them
  // that turns it on.
  let entries: Dirent[]
  try {
    entries = readdirSync(dir, { withFileTypes: true })
  } catch {
    return []
  }

  const out: string[] = []
  for (const entry of entries) {
    if (entry.isFile() && /^page\.(tsx|ts|jsx|js)$/.test(entry.name)) {
      out.push(prefix === '' ? '/' : prefix)
    }
    if (entry.isDirectory()) {
      if (NOT_A_ROUTE_DIR.test(entry.name)) continue
      out.push(...discoverRoutes(join(dir, entry.name), `${prefix}/${entry.name}`))
    }
  }
  return out
}

type SitemapEntry = {
  path: string
  changeFrequency: MetadataRoute.Sitemap[number]['changeFrequency']
  priority: number
}

// Priority schema: 1.0 for the front page, 0.5 for everything else. The capture
// carries no signal that would distinguish a section landing page from a post,
// so a finer gradient here would be decoration, not information.
// Trailing slash, to match `trailingSlash: true` and the per-page canonical.
// Without it the sitemap advertises 593 URLs that every page's own
// rel=canonical contradicts, and that the host answers with a 301 — measured:
// sitemap `…/about-us` against canonical `…/about-us/`. A crawler is being
// told two different addresses for one page by the same site.
const asServed = (path: string) => (path.endsWith('/') ? path : `${path}/`)

export const routes: readonly SitemapEntry[] = discoverRoutes()
  .sort()
  .map((path) => ({
    path: asServed(path),
    changeFrequency: 'monthly' as const,
    priority: path === '/' ? 1.0 : 0.5,
  }))

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()
  return routes.map((entry) => ({
    url: siteUrl(entry.path),
    lastModified: now,
    changeFrequency: entry.changeFrequency,
    priority: entry.priority,
  }))
}
