import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: {
    absolute: 'Obedience - Difficult Seasons: Episode 7 | Viewpoint Ministries International',
  },
  description:
    'Now you know there are different voices based on episode 6 "The Voice" and the most important among all the voices is the voice of God then it is ...',
  alternates: { canonical: '/obedience-difficult-seasons-episode-7-2/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-2789 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('obedience-difficult-seasons-episode-7-2'),
      }}
    />
  )
}
