import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      'In A Time Like This: Difficult Seasons - Episode 8 | Viewpoint Ministries International',
    description:
      'We cannot survive this time without God, and in a time like this, I pray “…He who has begun a good work in you will complete it until the day of Jesus Chris ...',
    canonical: '/in-a-time-like-this-difficult-seasons-episode-8/',
  }),
  title: {
    absolute:
      'In A Time Like This: Difficult Seasons - Episode 8 | Viewpoint Ministries International',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-501 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('in-a-time-like-this-difficult-seasons-episode-8'),
      }}
    />
  )
}
