import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Wait Until Your Change Comes | Viewpoint Ministries International',
    description:
      'Nobody likes to wait. Have you ever asked God what is taking you so long to fix the issues in your life? We know that God’s miracle is coming but we don’t l ...',
    canonical: '/wait-until-your-change-comes/',
  }),
  title: { absolute: 'Wait Until Your Change Comes | Viewpoint Ministries International' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1803 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('wait-until-your-change-comes') }}
    />
  )
}
