import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: 'Your Thoughts Your Life [Audio] | Viewpoint Ministries International',
  description:
    'https://anchor.fm/s/50014258/podcast/rss Summary In this episode, we bring you a message “Your Thoughts Your Life” To support this podcast please follow thi ...',
  alternates: { canonical: '/your-thoughts-your-life/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1392 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('your-thoughts-your-life') }}
    />
  )
}
