import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title:
    'The Reality of You, Your Faith, and Your Health W_ Dr. Deji Alabi | Viewpoint Ministries International',
  description:
    'Our health matters and in it there is a place for faith, and a place for wisdom that God has given to men because God wants us to be in good health. 3 John ...',
  alternates: { canonical: '/the-reality-of-you-your-faith-and-your-health-w-dr-deji-alabi/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-896 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('the-reality-of-you-your-faith-and-your-health-w-dr-deji-alabi'),
      }}
    />
  )
}
