import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Your Thoughts Your Life | Viewpoint Ministries International',
    description:
      'In the last episode, I said, “if you don’t want to be helpless, stranded, and left behind as your journey through life, trust in God must be your anchor&quo ...',
    canonical: '/your-thoughts-your-life-2/',
  }),
  title: { absolute: 'Your Thoughts Your Life | Viewpoint Ministries International' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1397 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('your-thoughts-your-life-2') }}
    />
  )
}
