import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: {
    absolute: 'The Voice - Difficult Seasons: Episode 6 | Viewpoint Ministries International',
  },
  description:
    'The voice you listen to and obey is critical to whether you come out of the difficulties, stay there for more than normal, or perpetually remain in that sea ...',
  alternates: { canonical: '/the-voice-difficult-seasons-episode-6/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-2786 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('the-voice-difficult-seasons-episode-6'),
      }}
    />
  )
}
