import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: 'Black History Month—Black Lives Matter (1) | Viewpoint Ministries International',
  description:
    'The Scripture, as written: “Then God said, “Let Us make man in Our image, according to Our likeness…….”. (Genesis 1:26) “Man”, made in the image of God. Thi ...',
  alternates: { canonical: '/black-history-month-black-lives-matter-1/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1420 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('black-history-month-black-lives-matter-1'),
      }}
    />
  )
}
