import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: {
    absolute:
      'Politics: The Old-Time Game in Our Contemporary World (5)￼ | Viewpoint Ministries International',
  },
  description:
    'Chief Obafemi Awolowo, in interrogating the colonial creation of Nigeria as a “Nation-State” stated as follows: “if rapid political progress is to be made i ...',
  alternates: { canonical: '/politics-the-old-time-game-in-our-contemporary-world-5-ef-bf-bc/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1315 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('politics-the-old-time-game-in-our-contemporary-world-5-ef-bf-bc'),
      }}
    />
  )
}
