import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'improveyourself | Viewpoint Ministries International' },
  description:
    'Make It Happen by Viewpoint Ministries | Jul 10, 2022 | MY VIEW No matter how unfair life seems or how often you may have failed in the past, you can still…',
  alternates: { canonical: '/tag/improveyourself/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tag tag-improveyourself tag-349 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_archives dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter osx et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('tag/improveyourself') }}
    />
  )
}
