import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: 'Sharing in His Crucifixion | Viewpoint Ministries International',
  description:
    'The death on the cross put an end to Adamic nature and an end to condemnation; the old is crucified and no longer existing. Now we have been made new throug ...',
  alternates: { canonical: '/sharing-in-his-crucifixion-2/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-475 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('sharing-in-his-crucifixion-2') }}
    />
  )
}
