import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: {
    absolute: "Fasting + Weight Gain: Let's Talk About It (2) | Viewpoint Ministries International",
  },
  description:
    'Sub-optimal food choices for breaking a fast Do you ever wonder what to eat after a period of fasting? The truth is that the food you break the fast with is ...',
  alternates: { canonical: '/fasting-weight-gain-lets-talk-about-it-2/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1387 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('fasting-weight-gain-lets-talk-about-it-2'),
      }}
    />
  )
}
