import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: "Fasting + Weight Gain: Let's Talk About It (1) | Viewpoint Ministries International",
  description:
    'Do you gain weight when you fast? Are you fasting but it seems like your waistline is having a feast? Do you dread looking at the number on your scale after ...',
  alternates: { canonical: '/fasting-weight-gain-lets-talk-about-it-1/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1382 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('fasting-weight-gain-lets-talk-about-it-1'),
      }}
    />
  )
}
