import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'mansion | Viewpoint Ministries International',
    description:
      'Your Mansion Await You If You Can Do This by Viewpoint Ministries | Apr 18, 2022 | MY VIEW , PODCASTS [Echo From Sharing in His Crucifixion] Jesus said…',
    canonical: '/tag/mansion/',
  }),
  title: { absolute: 'mansion | Viewpoint Ministries International' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tag tag-mansion tag-62 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_archives dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('tag/mansion') }}
    />
  )
}
