import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      'When worship becomes a lifestyle With Minister Timothy Ohikhueme (2 of 2) | Viewpoint Ministries International',
    description:
      'https://anchor.fm/s/50014258/podcast/rss Summary To watch video please visit: https://youtu.be/ABOebnuARro Transcription',
    canonical: '/when-worship-becomes-a-lifestyle-with-minister-timothy-ohikhueme-2-of-2/',
  }),
  title: {
    absolute:
      'When worship becomes a lifestyle With Minister Timothy Ohikhueme (2 of 2) | Viewpoint Ministries International',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-496 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent(
          'when-worship-becomes-a-lifestyle-with-minister-timothy-ohikhueme-2-of-2'
        ),
      }}
    />
  )
}
