import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Proclaim Your Confidence in God | Viewpoint Ministries International',
    description:
      'King David loved to praise the Lord. He was not afraid to proclaim his confidence in God. While in the mist of challenges, you don’t have to live with a def ...',
    canonical: '/proclaim-your-confidence-in-god/',
  }),
  title: { absolute: 'Proclaim Your Confidence in God | Viewpoint Ministries International' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1599 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('proclaim-your-confidence-in-god') }}
    />
  )
}
