// Generated by workflow 706 (integrate-clone-into-nextjs.mjs). Edit the
// template in FFC-Cloudflare-Automation/assets/clone-sitemap.test.ts, not this
// copy.
//
// Replaces the template's sitemap test, which diffed the sitemap against
// `src/app/**/page.tsx`. That invariant was right for a repo whose pages are
// app routes and is meaningless here: the conversion moves every template route
// into `_disabled_template_routes/` precisely so the captured pages under
// `public/` do not collide with them, so the old test compared a list of eight
// routes against an empty directory.
//
// The property it protected — the sitemap cannot silently fall behind what is
// published — is kept and retargeted at where the pages now live. It also
// covers rather more: every captured page, not eight template ones.
import fs from 'fs'
import path from 'path'
import sitemap, { routes, discoverExportedPages, PUBLIC_DIR } from '../../src/app/sitemap'
import { siteConfig } from '../../src/lib/site.config'

describe('sitemap.ts', () => {
  it('lists every exported page exactly once', () => {
    const discovered = discoverExportedPages().sort()
    const sitemapPaths = routes.map((r) => r.path).sort()

    expect(sitemapPaths).toEqual(discovered)
  })

  it('contains no duplicate path entries', () => {
    const paths = routes.map((r) => r.path)
    expect(paths.length).toBe(new Set(paths).size)
  })

  it('emits absolute URLs prefixed with siteConfig.url', () => {
    const entries = sitemap()
    for (const e of entries) {
      expect(typeof e.url).toBe('string')
      expect(e.url.startsWith(siteConfig.url.replace(/\/$/, ''))).toBe(true)
    }
  })

  it('uses priority 1.0 for the root route only', () => {
    const root = routes.find((r) => r.path === '/')
    expect(root?.priority).toBe(1.0)
    for (const r of routes) {
      if (r.path !== '/') expect(r.priority).toBeLessThan(1.0)
    }
  })

  // A capture that lost its front page is the failure mode this whole
  // migration has actually hit, and it is invisible in a count: 588 correct
  // pages and no index.html still reads as a near-complete site.
  it('includes the front page', () => {
    expect(routes.map((r) => r.path)).toContain('/')
  })

  // The sitemap is built by walking the filesystem, so it must not wander into
  // the capture's asset tree — a stray index.html in there would publish an
  // asset directory as a page.
  it('never lists a path inside the asset tree', () => {
    for (const r of routes) {
      expect(r.path.startsWith('/_')).toBe(false)
      expect(r.path.startsWith('/.')).toBe(false)
    }
  })

  // Discovery is what the first three tests are really asserting, and all of
  // them pass vacuously on an empty list. This is the case that fails when the
  // walk silently stops finding anything.
  it('discovers the pages that are actually on disk', () => {
    const onDisk = fs
      .readdirSync(PUBLIC_DIR, { withFileTypes: true })
      .filter((e) => e.isDirectory() && !/^[._]/.test(e.name))
      .filter((e) => fs.existsSync(path.join(PUBLIC_DIR, e.name, 'index.html'))).length

    if (onDisk === 0) return // a repo with no capture yet has nothing to check
    const topLevel = routes.filter((r) => r.path !== '/' && r.path.lastIndexOf('/') === 0).length
    expect(topLevel).toBe(onDisk)
  })
})
