// Generated by workflow 706 (convert-clone-to-routes.mjs). Edit the template in
// FFC-Cloudflare-Automation/assets/clone-routes-sitemap.test.ts, not this copy.
//
// Replaces the template's sitemap test, which diffed the sitemap against a
// hand-maintained array of eight routes. The property it protected — the
// sitemap cannot silently fall behind what is published — is kept, and now
// covers every converted page rather than eight template ones.
import fs from 'fs'
import path from 'path'
import sitemap, { routes, discoverRoutes, APP_DIR } from '../../src/app/sitemap'
import { siteConfig } from '../../src/lib/site.config'

describe('sitemap.ts', () => {
  it('lists every route exactly once', () => {
    expect(routes.map((r) => r.path).sort()).toEqual(
      discoverRoutes()
        .map((p) => (p.endsWith('/') ? p : `${p}/`))
        .sort()
    )
  })

  // next.config sets `trailingSlash: true`, so every page is served at — and
  // canonicalises to — its slashed URL. A sitemap that advertises the slashless
  // form tells a crawler a different address than the page itself does, and the
  // host answers it with a 301.
  it('advertises the URL each page is actually served at', () => {
    for (const r of routes) expect(r.path.endsWith('/')).toBe(true)
  })

  it('contains no duplicate path entries', () => {
    const paths = routes.map((r) => r.path)
    expect(paths.length).toBe(new Set(paths).size)
  })

  it('emits absolute URLs prefixed with siteConfig.url', () => {
    for (const e of sitemap()) {
      expect(typeof e.url).toBe('string')
      expect(e.url.startsWith(siteConfig.url.replace(/\/$/, ''))).toBe(true)
    }
  })

  it('uses priority 1.0 for the root route only', () => {
    expect(routes.find((r) => r.path === '/')?.priority).toBe(1.0)
    for (const r of routes) {
      if (r.path !== '/') expect(r.priority).toBeLessThan(1.0)
    }
  })

  // A capture that lost its front page is the failure mode this migration has
  // actually hit, and it is invisible in a count: 586 correct pages and no
  // index still reads as a near-complete site.
  it('includes the front page', () => {
    expect(routes.map((r) => r.path)).toContain('/')
  })

  // The walk must not descend into a route group or a private folder: neither
  // is a URL, so listing one advertises a page that does not exist.
  it('never lists a route-group or private path', () => {
    for (const r of routes) {
      expect(r.path).not.toMatch(/\/[(_[]/)
    }
  })

  // Discovery is what the tests above are really asserting, and every one of
  // them passes vacuously on an empty list. This is the case that fails when
  // the walk silently stops finding anything.
  it('discovers the routes that are actually on disk', () => {
    const onDisk = fs
      .readdirSync(APP_DIR, { withFileTypes: true })
      .filter((e) => e.isDirectory() && !/^[(_[]/.test(e.name))
      .filter((e) => fs.existsSync(path.join(APP_DIR, e.name, 'page.tsx'))).length

    // Depth by SEGMENT count, not by the position of a '/': every path now
    // ends in one, so `lastIndexOf('/') === 0` matched nothing and this
    // assertion silently compared 253 against 0.
    const depth = (p: string) => p.split('/').filter(Boolean).length
    const topLevel = routes.filter((r) => depth(r.path) === 1).length
    expect(onDisk).toBeGreaterThan(0)
    expect(topLevel).toBe(onDisk)
  })
})
