import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'worry | Viewpoint Ministries International' },
  description:
    'Do Not Worry by Viewpoint Ministries | Mar 30, 2022 | MY VIEW When you have an issue or concern that is troubling you, tell God what you need. Give God…',
  alternates: { canonical: '/tag/worry/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tag tag-worry tag-244 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_archives dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('tag/worry') }}
    />
  )
}
