import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'E-Tracts | Viewpoint Ministries International',
    description:
      '“And he said to them, “go into all the world and preach the gospel to every creature” (Mark 16:15). Click on the title below to view and read. Feel free to ...',
    canonical: '/etracts/',
  }),
  title: { absolute: 'E-Tracts | Viewpoint Ministries International' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-70 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_pb_pagebuilder_layout et_no_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('etracts') }}
    />
  )
}
