import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      'Discernment_ Critical Ingredient For Daily Living In The Era Of Technology w_ Dr. T. Oni and Dr. T. Ajagemo | Viewpoint Ministries International',
    description:
      'Technology, when used positively, could yield enormous results. The impact of technology cannot be over-emphasized. It remains a critical part of our daily ...',
    canonical:
      '/discernment-critical-ingredient-for-daily-living-in-the-era-of-technology-w-dr-t-oni-and-dr-t-ajagemo/',
  }),
  title: {
    absolute:
      'Discernment_ Critical Ingredient For Daily Living In The Era Of Technology w_ Dr. T. Oni and Dr. T. Ajagemo | Viewpoint Ministries International',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-843 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent(
          'discernment-critical-ingredient-for-daily-living-in-the-era-of-technology-w-dr-t-oni-and-dr-t-ajagemo'
        ),
      }}
    />
  )
}
