import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'fear | Viewpoint Ministries International' },
  description:
    'Fear or Not to Fear by Viewpoint Ministries | May 1, 2022 | MY VIEW , PODCASTS The fear of the Lord is the beginning of wisdom (Proverbs 9:10), NOT the…',
  alternates: { canonical: '/tag/fear/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tag tag-fear tag-115 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_archives dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('tag/fear') }}
    />
  )
}
