import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: 'Fear: The Enemy of Progress | Viewpoint Ministries International',
  description:
    'When you anticipate success and breakthrough is around the corner, do not entertain fear, do not start to doubt your breakthrough. Never allow your emotion ...',
  alternates: { canonical: '/fear-the-enemy-of-progress/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-847 single-format-gallery wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer dtb_blog_default toolbox_menu4 et_button_no_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('fear-the-enemy-of-progress') }}
    />
  )
}
